[project]
name = "experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "lark-oapi>=1.4.17",
    "loguru>=0.7.3",
    "mcp[cli]>=1.6.0",
    "pydantic>=2.10.5",
    "rich>=13.9.4",
]
